name: Release Scheduler
on:
  workflow_dispatch:
jobs:
  dispatch_scheduled_releases:
    name: Dispatch scheduled releases
    if: github.repository_owner == 'spring-projects'
    strategy:
      matrix:
        # List of active maintenance branches.
        branch: [ main, 6.0.x, 5.8.x, 5.7.x ]
    runs-on: ubuntu-22.04
  workflow_dispatch:
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Dispatch
      env:
        GH_TOKEN: ${{ secrets.GH_ACTIONS_REPO_TOKEN }}
      run: gh workflow run update-scheduled-release-version.yml -r ${{ matrix.branch }}
